
import core.Agent;
import core.Enseignant;
import core.Etudiant;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author fredy
 */
public class EnregistrerContact extends javax.swing.JFrame {

    /**
     * Creates new form EnregistrerContact
     */
    public EnregistrerContact() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backButtonSaveContact = new javax.swing.JButton();
        validationSaveButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        panelActif = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane15 = new javax.swing.JScrollPane();
        etudiantCodeEntry = new javax.swing.JEditorPane();
        jScrollPane19 = new javax.swing.JScrollPane();
        etudiantEmailEntry = new javax.swing.JEditorPane();
        etudiantCycleEntry = new javax.swing.JComboBox<>();
        etudiantNiveauEntry = new javax.swing.JComboBox<>();
        jScrollPane22 = new javax.swing.JScrollPane();
        etudiantNomEntry = new javax.swing.JEditorPane();
        jScrollPane23 = new javax.swing.JScrollPane();
        etudiantDateEntry = new javax.swing.JEditorPane();
        jScrollPane24 = new javax.swing.JScrollPane();
        etudiantAddressEntry = new javax.swing.JEditorPane();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane25 = new javax.swing.JScrollPane();
        etudiantPhoneEntry = new javax.swing.JEditorPane();
        jPanel3 = new javax.swing.JPanel();
        agentNomLabel = new javax.swing.JLabel();
        agentCodeLabel = new javax.swing.JLabel();
        agentDateLabel = new javax.swing.JLabel();
        agentAddressLabel = new javax.swing.JLabel();
        agentSalaireLabel = new javax.swing.JLabel();
        agentEmailLabel = new javax.swing.JLabel();
        agentStatutLabel = new javax.swing.JLabel();
        agentCategorieLabel = new javax.swing.JLabel();
        agentIndiceLabel = new javax.swing.JLabel();
        agentOccupationLabel = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        agentCodeEntry = new javax.swing.JEditorPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        agentNomEntry = new javax.swing.JEditorPane();
        jScrollPane9 = new javax.swing.JScrollPane();
        agentOccupationEntry = new javax.swing.JEditorPane();
        jScrollPane10 = new javax.swing.JScrollPane();
        agentEmailEntry = new javax.swing.JEditorPane();
        jScrollPane11 = new javax.swing.JScrollPane();
        agentPhoneEntry = new javax.swing.JEditorPane();
        agentStatutEntry = new javax.swing.JComboBox<>();
        jScrollPane13 = new javax.swing.JScrollPane();
        agentAddressEntry = new javax.swing.JEditorPane();
        jScrollPane14 = new javax.swing.JScrollPane();
        agentIndiceEntry = new javax.swing.JEditorPane();
        jScrollPane20 = new javax.swing.JScrollPane();
        agentCategorieEntry = new javax.swing.JEditorPane();
        jScrollPane21 = new javax.swing.JScrollPane();
        agentDateEntry = new javax.swing.JEditorPane();
        agentSalaireLabel1 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        agentSalaireEntry = new javax.swing.JEditorPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        codeEnsEntry = new javax.swing.JEditorPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        nomEnsEntry = new javax.swing.JEditorPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        dateEnsEntry = new javax.swing.JEditorPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        addressEnsEntry = new javax.swing.JEditorPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        emailEnsEntry = new javax.swing.JEditorPane();
        statutEnsEntry = new javax.swing.JComboBox<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        phoneEnsEntry = new javax.swing.JEditorPane();
        jLabel31 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ENREGISTREMENT DE CONTACT");

        jPanel1.setBackground(new java.awt.Color(64, 64, 64));

        backButtonSaveContact.setText("Retour");
        backButtonSaveContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonSaveContactActionPerformed(evt);
            }
        });

        validationSaveButton.setText("Valider");
        validationSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validationSaveButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Enregistrer");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(backButtonSaveContact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(validationSaveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(saveButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(validationSaveButton)
                .addGap(18, 18, 18)
                .addComponent(backButtonSaveContact)
                .addGap(35, 35, 35)
                .addComponent(saveButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelActif.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                panelActifStateChanged(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel19.setText("code");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("nom");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel20.setText("date");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel21.setText("address");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel22.setText("email");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel23.setText("cycle");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel24.setText("niveau");

        jScrollPane15.setViewportView(etudiantCodeEntry);

        jScrollPane19.setViewportView(etudiantEmailEntry);

        etudiantCycleEntry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Licence", "Ingenieur" }));

        etudiantNiveauEntry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        jScrollPane22.setViewportView(etudiantNomEntry);

        jScrollPane23.setViewportView(etudiantDateEntry);

        jScrollPane24.setViewportView(etudiantAddressEntry);

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel29.setText("phone");

        jScrollPane25.setViewportView(etudiantPhoneEntry);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel19))
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24)
                    .addComponent(jLabel29))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane15)
                    .addComponent(jScrollPane22)
                    .addComponent(jScrollPane23)
                    .addComponent(jScrollPane24)
                    .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane25, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(etudiantCycleEntry, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etudiantNiveauEntry, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(124, 124, 124))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 40, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane15, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane22, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                        .addGap(31, 31, 31)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane23)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane24))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21)
                        .addGap(0, 23, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel29)
                    .addComponent(jScrollPane25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(etudiantCycleEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(etudiantNiveauEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(175, Short.MAX_VALUE))
        );

        panelActif.addTab("Etudiant", jPanel2);

        agentNomLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        agentNomLabel.setText("nom");

        agentCodeLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        agentCodeLabel.setText("code");

        agentDateLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        agentDateLabel.setText("date");

        agentAddressLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        agentAddressLabel.setText("address");

        agentSalaireLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        agentSalaireLabel.setText("salaire");

        agentEmailLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        agentEmailLabel.setText("email");

        agentStatutLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        agentStatutLabel.setText("statut");

        agentCategorieLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        agentCategorieLabel.setText("categorie");

        agentIndiceLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        agentIndiceLabel.setText("indice");

        agentOccupationLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        agentOccupationLabel.setText("occupation");

        jScrollPane7.setViewportView(agentCodeEntry);

        jScrollPane8.setViewportView(agentNomEntry);

        jScrollPane9.setViewportView(agentOccupationEntry);

        jScrollPane10.setViewportView(agentEmailEntry);

        jScrollPane11.setViewportView(agentPhoneEntry);

        agentStatutEntry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "temporaire", "stagiaire", "permanent" }));

        jScrollPane13.setViewportView(agentAddressEntry);

        jScrollPane14.setViewportView(agentIndiceEntry);

        jScrollPane20.setViewportView(agentCategorieEntry);

        jScrollPane21.setViewportView(agentDateEntry);

        agentSalaireLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        agentSalaireLabel1.setText("phone");

        jScrollPane12.setViewportView(agentSalaireEntry);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(agentOccupationLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(agentEmailLabel)
                                            .addGap(58, 58, 58))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                            .addComponent(agentSalaireLabel1)
                                            .addGap(40, 40, 40)))
                                    .addComponent(agentCategorieLabel)
                                    .addComponent(agentIndiceLabel)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(agentSalaireLabel)
                                        .addComponent(agentStatutLabel)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                                    .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(jScrollPane14, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(jScrollPane20, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE))
                                    .addComponent(jScrollPane12, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(agentStatutEntry, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(agentCodeLabel)
                        .addGap(69, 69, 69)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(agentNomLabel)
                        .addGap(73, 73, 73)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(agentDateLabel)
                        .addGap(73, 73, 73)
                        .addComponent(jScrollPane21, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(agentAddressLabel)
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane13, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)))
                .addGap(93, 93, 93))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(agentCodeLabel)
                    .addComponent(jScrollPane7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(agentNomLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(agentDateLabel)
                    .addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(agentAddressLabel)
                    .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(agentEmailLabel)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                        .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(agentSalaireLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(agentSalaireLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(agentStatutLabel)
                            .addComponent(agentStatutEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addComponent(agentCategorieLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(agentIndiceLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(agentOccupationLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelActif.addTab("Agent", jPanel3);

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel25.setText("code");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("nom");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel26.setText("date");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel27.setText("address");

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel28.setText("email");

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel30.setText("statut");

        jScrollPane1.setViewportView(codeEnsEntry);

        jScrollPane2.setViewportView(nomEnsEntry);

        jScrollPane3.setViewportView(dateEnsEntry);

        jScrollPane4.setViewportView(addressEnsEntry);

        jScrollPane5.setViewportView(emailEnsEntry);

        statutEnsEntry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "vacataire", "permanent" }));

        jScrollPane6.setViewportView(phoneEnsEntry);

        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel31.setText("phone");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel25)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel26)
                            .addGap(1, 1, 1))
                        .addComponent(jLabel4))
                    .addComponent(jLabel27)
                    .addComponent(jLabel28)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31))
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(statutEnsEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                        .addComponent(jScrollPane2)
                        .addComponent(jScrollPane3)
                        .addComponent(jScrollPane4)
                        .addComponent(jScrollPane5)
                        .addComponent(jScrollPane6)))
                .addContainerGap(218, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4)
                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(47, 47, 47)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel30)
                    .addComponent(statutEnsEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(230, Short.MAX_VALUE))
        );

        panelActif.addTab("Enseignant", jPanel4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelActif)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(panelActif)
        );

        panelActif.getAccessibleContext().setAccessibleName("panelChangeant");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void validationSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validationSaveButtonActionPerformed
        if(panelActif.getSelectedIndex() == 0){
            String codeEtudiant = etudiantCodeEntry.getText();
            String nomEtudiant = etudiantNomEntry.getText();
            String dateEtudiant = etudiantDateEntry.getText();
            String addressEtudiant = etudiantAddressEntry.getText();
            String emailEtudiant = etudiantEmailEntry.getText();
            String telEtudiant = etudiantPhoneEntry.getText();
            String cycleEtudiant = etudiantCycleEntry.getSelectedItem().toString();
            String niveauEtudiant = etudiantNiveauEntry.getSelectedItem().toString();
            Etudiant etudiant = new Etudiant(codeEtudiant, nomEtudiant, dateEtudiant,addressEtudiant, emailEtudiant, telEtudiant,cycleEtudiant,niveauEtudiant  );
            
            MainFramApplication.repertoire.ajouterContact(etudiant);
            
        }else if(panelActif.getSelectedIndex() == 1){
            String codeAgent = agentCodeEntry.getText();
            String nomAgent = agentNomEntry.getText();
            String dateAgent = agentDateEntry.getText();
            String addressAgent = agentAddressEntry.getText();
            String emailAgent = agentEmailEntry.getText();
            String telAgent = agentPhoneEntry.getText();
            String salaireAgent = agentSalaireEntry.getText();
            String statutAgent = agentStatutEntry.getSelectedItem().toString();
            String categorieAgent = agentCategorieEntry.getText();
            int indiceSalaireAgent = Integer.parseInt(agentIndiceEntry.getText());
            String occupationAgent = agentOccupationEntry.getText();
            
            Agent agent = new Agent(codeAgent,nomAgent,dateAgent, addressAgent, emailAgent, telAgent, salaireAgent, statutAgent, categorieAgent, indiceSalaireAgent, occupationAgent);
            MainFramApplication.repertoire.ajouterContact(agent);
        }else if(panelActif.getSelectedIndex() == 2){
            String codeAgent = codeEnsEntry.getText();
            String nomAgent = nomEnsEntry.getText();
            String dateAgent = dateEnsEntry.getText();
            String addressAgent = addressEnsEntry.getText();
            String emailAgent = emailEnsEntry.getText();
            String telAgent = phoneEnsEntry.getText();
            String statutAgent = statutEnsEntry.getSelectedItem().toString();
            
            Enseignant ens = new Enseignant(codeAgent,nomAgent,dateAgent, addressAgent, emailAgent, telAgent, statutAgent);
            MainFramApplication.repertoire.ajouterContact(ens);
        }
        
        
    }//GEN-LAST:event_validationSaveButtonActionPerformed

    private void backButtonSaveContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonSaveContactActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_backButtonSaveContactActionPerformed

    private void panelActifStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_panelActifStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_panelActifStateChanged

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        MainFramApplication.enregistrer();
    }//GEN-LAST:event_saveButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnregistrerContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnregistrerContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnregistrerContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnregistrerContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnregistrerContact().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane addressEnsEntry;
    private javax.swing.JEditorPane agentAddressEntry;
    private javax.swing.JLabel agentAddressLabel;
    private javax.swing.JEditorPane agentCategorieEntry;
    private javax.swing.JLabel agentCategorieLabel;
    private javax.swing.JEditorPane agentCodeEntry;
    private javax.swing.JLabel agentCodeLabel;
    private javax.swing.JEditorPane agentDateEntry;
    private javax.swing.JLabel agentDateLabel;
    private javax.swing.JEditorPane agentEmailEntry;
    private javax.swing.JLabel agentEmailLabel;
    private javax.swing.JEditorPane agentIndiceEntry;
    private javax.swing.JLabel agentIndiceLabel;
    private javax.swing.JEditorPane agentNomEntry;
    private javax.swing.JLabel agentNomLabel;
    private javax.swing.JEditorPane agentOccupationEntry;
    private javax.swing.JLabel agentOccupationLabel;
    private javax.swing.JEditorPane agentPhoneEntry;
    private javax.swing.JEditorPane agentSalaireEntry;
    private javax.swing.JLabel agentSalaireLabel;
    private javax.swing.JLabel agentSalaireLabel1;
    private javax.swing.JComboBox<String> agentStatutEntry;
    private javax.swing.JLabel agentStatutLabel;
    private javax.swing.JButton backButtonSaveContact;
    private javax.swing.JEditorPane codeEnsEntry;
    private javax.swing.JEditorPane dateEnsEntry;
    private javax.swing.JEditorPane emailEnsEntry;
    private javax.swing.JEditorPane etudiantAddressEntry;
    private javax.swing.JEditorPane etudiantCodeEntry;
    private javax.swing.JComboBox<String> etudiantCycleEntry;
    private javax.swing.JEditorPane etudiantDateEntry;
    private javax.swing.JEditorPane etudiantEmailEntry;
    private javax.swing.JComboBox<String> etudiantNiveauEntry;
    private javax.swing.JEditorPane etudiantNomEntry;
    private javax.swing.JEditorPane etudiantPhoneEntry;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane22;
    private javax.swing.JScrollPane jScrollPane23;
    private javax.swing.JScrollPane jScrollPane24;
    private javax.swing.JScrollPane jScrollPane25;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JEditorPane nomEnsEntry;
    private javax.swing.JTabbedPane panelActif;
    private javax.swing.JEditorPane phoneEnsEntry;
    private javax.swing.JButton saveButton;
    private javax.swing.JComboBox<String> statutEnsEntry;
    private javax.swing.JButton validationSaveButton;
    // End of variables declaration//GEN-END:variables
}
