
//import static MainApplication.connection;
import core.Agent;
import core.Contact;
import core.Enseignant;
import core.Etudiant;
import core.Repertoire;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.Map.Entry;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author fredy
 */
public class MainFramApplication extends javax.swing.JFrame {
    public static Connection connection ;
    public static Repertoire repertoire =  new Repertoire();
    
    
    
    
    
    public MainFramApplication(Repertoire repertoire) {
        this.repertoire = repertoire;

    }
    
    public static void enregistrer( ){
        for (Entry<String, Contact> entry: MainFramApplication.repertoire.getListeDeContact().entrySet()){
            Contact contact = entry.getValue();
            try {
                if(contact instanceof Etudiant) {
                    Etudiant etudiant = (Etudiant) contact;
                    etudiant.insererContact(connection);
                } else if (contact instanceof Enseignant) {
                    Enseignant enseignant = (Enseignant) contact;
                    enseignant.insererContact(connection);
                } else if (contact instanceof Agent) {
                    Agent agent = (Agent) contact;
                    agent.insererContact(connection);
                }
                System.out.println("Enregistement reuissi");
            }catch(Exception e){
                e.printStackTrace();
            }
        }
    }
    /**
     * Creates new form MainFramApplication
     */
    public MainFramApplication() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        enregistrerContactButton = new javax.swing.JButton();
        affichageContactButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("BIENVENUE DANS NOTRE APPLICATION DE GESTION DE CONTACT");

        enregistrerContactButton.setText("ENREGISTRER UN NOUVEAU CONTACT");
        enregistrerContactButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enregistrerContactButtonActionPerformed(evt);
            }
        });

        affichageContactButton.setText("CONSULTER LISTE DES CONTACT");
        affichageContactButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                affichageContactButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(enregistrerContactButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(affichageContactButton)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(enregistrerContactButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(affichageContactButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enregistrerContactButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enregistrerContactButtonActionPerformed
        EnregistrerContact enre = new EnregistrerContact();
        enre.setVisible(true);
    }//GEN-LAST:event_enregistrerContactButtonActionPerformed

    private void affichageContactButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_affichageContactButtonActionPerformed
        AfficherContact aff = new AfficherContact();
        aff.setVisible(true);
        
    }//GEN-LAST:event_affichageContactButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        String jdbcUrl = "jdbc:mysql://localhost:3306/minitp"; // URL de connexion à la base de données
        String username = "fredy"; // Nom d'utilisateur MySQL
        String password = "12021997"; 
  
        System.out.println("MainFrmApplication: database connection succes");
        
        try{
            connection = DriverManager.getConnection(jdbcUrl, username, password);
        }catch(SQLException e){
            e.printStackTrace();
            connection = null;
            System.out.println("MainFrmApplication: database connection faillure");
        }
        
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFramApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFramApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFramApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFramApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFramApplication().setVisible(true);
            }
        });
    }
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton affichageContactButton;
    private javax.swing.JButton enregistrerContactButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
